<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DesktopCalendar.Core.Desktop\DesktopCalendar.Core.Desktop.csproj" />
    <ProjectReference Include="..\DesktopCalendar.Core.Calendar\DesktopCalendar.Core.Calendar.csproj" />
    <ProjectReference Include="..\DesktopCalendar.Core.Holiday\DesktopCalendar.Core.Holiday.csproj" />
    <ProjectReference Include="..\DesktopCalendar.Core.Google\DesktopCalendar.Core.Google.csproj" />
    <ProjectReference Include="..\DesktopCalendar.Core.Storage\DesktopCalendar.Core.Storage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\calendar.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\calendar.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
